# Generated by Django 4.2.7 on 2023-12-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_publicaciones_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'ordering': ('fecha',)},
        ),
    ]
