# Generated by Django 4.2.7 on 2023-12-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_alter_publicaciones_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='nota',
        ),
    ]
