# Generated by Django 4.2.7 on 2023-12-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_remove_publicaciones_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'ordering': ('-fecha',)},
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='publicado',
        ),
    ]
